project_name: ticker
before:
  hooks:
    - go mod download
builds:
  - id: build-mac
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    ldflags:
      - -s -w -X 'github.com/hwyll/ticker/cmd.Version={{.Version}}'
archives:
  - id: release
    format: tar.gz
    name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}mac
      {{- else}}{{ .Os }}{{ end }}-
      {{- .Arch }}
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
release:
  github:
    owner: hwyll
    name: ticker
brews:
  - name: ticker
    repository:
      owner: hwyll
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    commit_author:
      name: hwyll
      email: hwyll@users.noreply.github.com 
    homepage: "https://github.com/hwyll/ticker"
    description: "Terminal stock ticker with live updates and position tracking"
    license: "GPLv3"
    install: |
      bin.install "ticker"
